Docker Chal Gyagit add .!

diff --git a/.github/workflows/chai-code-deploy.yml b/.github/workflows/chai-code-deploy.yml
--- a/.github/workflows/chai-code-deploy.yml
+++ b/.github/workflows/chai-code-deploy.yml
@@ -14,22 +14,22 @@ jobs:
         - name: Checkout Code
           uses: actions/checkout@v4
 
-        # - name: Login to Docker Hub
-        #   uses: docker/login-action@v4
-        #   with:
-        #     username: ${{ vars.DOCKERHUB_USERNAME }}
-        #     password: ${{ secrets.DOCKERHUB_TOKEN }}
+        - name: Login to Docker Hub
+          uses: docker/login-action@v4
+          with:
+            username: ${{ vars.DOCKERHUB_USERNAME }}
+            password: ${{ secrets.DOCKERHUB_TOKEN }}
 
-        # - name: QEMU
-        #   uses: docker/setup-qemu-action@v4
+        - name: QEMU
+          uses: docker/setup-qemu-action@v4
       
-        # - name: Set up Docker Buildx
-        #   uses: docker/setup-buildx-action@v4
+        - name: Set up Docker Buildx
+          uses: docker/setup-buildx-action@v4
 
-        # - name: Docker Build and Push
-        #   run: 
-        #     docker build -t gaurangkanbur/node-image .
-        #     docker push gaurangkanbur/node-image
+        - name: Docker Build and Push
+          run: 
+            docker build -t gaurangkanbur/node-image .
+            docker push gaurangkanbur/node-image
 
 
 
@@ -40,10 +40,15 @@ jobs:
             username: ubuntu
             key: ${{ secrets.PRIVATE_KEY }}
             script: |
-              export NVM_DIR="$HOME/.nvm"
-              [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
-              cd /home/ubuntu/Chai-Devops
-              git pull
-              npm install
-              pm2 restart 0
+               sudo docker rm -f node-image || true
+
+               # Again pull the fresh image from hub
+                 sudo docker pull gaurangkanbur/node-image
+
+               # Run container
+                sudo docker run -d --name node-image --restart unless-stopped -p 80:8000 gaurangkanbur/node-image
+
+               # Clean up old/unused images
+                 sudo docker image prune -f
+
              
